language: java
sudo: false
notifications:
  hipchat:
    rooms:
      secure: gOZBKLvyLBhPKC0tZcdrY7H/PUW1NePd41kjnVaZYHj/7dpqhNQ8zm1AhtIdZ16eswXiRjPMUr9mNFzYDATOz6TrYZRlh6fiZTjnGkl41nUmfqNw6AEUzh4gF0fj6I7uNKW+5eDeIwap3jngVmUGviHaqWHcgYByf0Y56HQnODcO1bQIMxFQ8nDQySWr1TPZcdoolKLFzHaJPvC+Mb0uilxRCpUqVVQfhIAibuCwvdmxOSoOwDM9u/Wp1HvefvkYy533xq6LgIjFtdihE4x5U1wrbOA8ch6ojuV6MErBUD79UXd5UXzB9uqiSS5vQTAl3pI/D/Emgx7FoPsCBDv2db8/QhlCUH54YZlyU5M/E6OBTS9XS6ApHfziE4C6uXGknhW1MFBgPLpFcZjICpb12/z8yPCoP3yYozRWNL5rguY7LNYAxHxfX9fZottUYYtjzG9T8fCOyIrwTH2B8g0NbyVTN3uPnJZ+pRF2HGsMJD1qm+TVYvxoL8grSb99hITRHwQZyDbmC+nkP/YXXcDf0VMJLwau7rR3T+1wSjLBnj+I9Dg3A0N9ytz7MIKcxJaevWgH2U3tjI/Kau8FICu+vRoeapEsQUI7uYxEYuIdOgv40g03btpIWJhHwScsM9Fjo4h6xYZ+KmfQJtp8wn2cdOi5CWDOT3xGXdKM4zk2ANA=
